export default [
  {
    category: "Computer",
    color: "cyan",
    items: {
        Trello: "https://trello.com/b/nuYOpstj/tareas-generales",
        Github: "https://github.com/SonidoCristalino?tab=repositories",
        AWS: "https://emiliano-aws-v2.signin.aws.amazon.com/console",
        WarGames: "https://overthewire.org/wargames/",
        "Greasy Fork": "https://greasyfork.org/es",
      // "Dev.to": "https://dev.to",
      // Firebase: "https://console.firebase.google.com/u/0",
    },
  },
  {
    category: "University",
    color: "red",
    items: {
        Pomodoro: "https://duckduckgo.com/?q=timer+20+minutes&ia=answer&ko=1&kae=d&kav=1",
        ChatGPT: "https://chatgpt.com/?model=auto",
        "ChatGPT Temporary": "https://chatgpt.com/?default=c&temporary-chat=true",
        Gemini: "https://gemini.google.com/app?hl=es-AR",
        Campus: "https://campus.unaj.edu.ar/",
      // Canvas: "https://sit.instructure.com",
      // MyStevens: "https://login.stevens.edu/app/UserHome",
    },
  },
  {
    category: "Work",
    color: "green",
    items: {
        Gmail: "https://mail.google.com/mail/u/0/#inbox",
        Calendar: "https://calendar.google.com/calendar/u/0/r/week",
        Drive: "https://drive.google.com/drive/u/0/home",
        "Usos Horarios": "https://www.zeitverschiebung.net/es/",
        "LI Messenger": "https://www.linkedin.com/messaging",
        "LI Recommended": "https://www.linkedin.com/jobs/collections/recommended",
        "LI Easy Apply": "https://www.linkedin.com/jobs/search/?alertAction=viewjobs&f_AL=true&origin=JOB_SEARCH_PAGE_JOB_FILTER",
        "LI Blink": "https://badoo.com/es-mx/people-nearby",
    },
  },
  {
    category: "Fun",
    color: "purple",
    items: {
        Whatsapp: "https://web.whatsapp.com/",
        "P!": "http://www.poringa.net/mi/",
        "P! Chat": "https://www.poringa.net/chat/",
        Wheater: "https://www.smn.gob.ar/",
        Pinterest: "https://ar.pinterest.com/",
        Odysee: "https://odysee.com/",
        "Biblioteca Secreta": "http://bibliotecasecreta.nl",
        "Yewtu.be": "https://yewtu.be",
        "Piped Video": "https://piped.wireway.ch/trending",
        // Twitter: "https://x.com/home",
        // Trakt: "https://trakt.tv/users/peterrauscher/lists",
        // Fmovies: "https://fmovies.to/home",
        // Zoro: "https://zoro.to",
        // TempMail: "https://tempmail.email/",
        // IPTorrents: "https://iptorrents.com/t",
    },
  },
  {
    category: "Business",
    color: "blue",
    items: {
        "Reddit Merval": "https://www.reddit.com/r/merval/search/?sort=new",
        "Dolar Hoy": "https://dolarhoy.com/",
        "Portfolio": "https://cuenta.portfoliopersonal.com/login",
        "ZonaProp": "https://www.zonaprop.com.ar/",
        "ArgenProp": "https://www.argenprop.com/",
        "Calculadora Inflación": "https://calculadoradeinflacion.com/",
        "Calculadora Porcentaje": "https://porcentaje.org/",
    },
  },
];
