export default [
  {
    category: "Computer",
    color: "cyan",
    items: {
        Trello: "https://trello.com/b/nuYOpstj/tareas-generales",
        Github: "https://github.com",
        AWS: "https://emiliano-aws-v2.signin.aws.amazon.com/console",
        WarGames: "https://overthewire.org/wargames/",
      // "Dev.to": "https://dev.to",
      // Firebase: "https://console.firebase.google.com/u/0",
    },
  },
  {
    category: "University",
    color: "red",
    items: {
        ChatGPT: "https://chatgpt.com/?model=auto",
        "ChatGPT Temporary": "https://chatgpt.com/?default=c&temporary-chat=true",
        Campus: "https://campus.unaj.edu.ar/",
      // Canvas: "https://sit.instructure.com",
      // MyStevens: "https://login.stevens.edu/app/UserHome",
    },
  },
  {
    category: "Work",
    color: "green",
    items: {
        Gmail: "https://mail.google.com/mail/u/0/#inbox",
        Calendar: "https://calendar.google.com/calendar/u/0/r/week",
        Drive: "https://drive.google.com/drive/u/0/home",
        "LI Messenger": "https://www.linkedin.com/messaging",
        "LI Recommended": "https://www.linkedin.com/jobs/collections/recommended",
        "LI Search": "https://www.linkedin.com/jobs/search/?alertAction=viewjobs&f_AL=true&origin=JOB_SEARCH_PAGE_JOB_FILTER",
    },
  },
  {
    category: "Fun",
    color: "purple",
    items: {
        Whatsapp: "https://web.whatsapp.com/",
        Poringa: "http://www.poringa.net/mi/",
        Wheater: "https://www.smn.gob.ar/",
        Pinterest: "https://ar.pinterest.com/",
        "Youtube Music": "https://music.youtube.com/",
        Odysee: "https://odysee.com/",
        "Biblioteca Secreta": "http://bibliotecasecreta.nl",
        "Yewtu.be": "https://yewtu.be",
        // Trakt: "https://trakt.tv/users/peterrauscher/lists",
        // Fmovies: "https://fmovies.to/home",
        // Zoro: "https://zoro.to",
        // TempMail: "https://tempmail.email/",
        // IPTorrents: "https://iptorrents.com/t",
    },
  },
  {
    category: "Business",
    color: "blue",
    items: {
        "Reddit Merval": "https://www.reddit.com/r/merval/search/?sort=new",
        "Dolar Hoy": "https://dolarhoy.com/",
        "Portfolio": "https://cuenta.portfoliopersonal.com/login",
        "ZonaProp": "https://www.zonaprop.com.ar/",
        "ArgenProp": "https://www.argenprop.com/",
    },
  },
];
